FROM node:17.3.1-alpine3.15
LABEL maintainer="Daniel Rataj <daniel.rataj@centrum.cz>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

RUN apk add --no-cache openssl=1.1.1l-r8 \
  docker-cli=20.10.11-r0 \
  && rm -rf /var/cache/apk/*

WORKDIR /app

# copy required app files
COPY alerting/ .
RUN npm install --quiet

# start alerting
CMD [ "npm", "start" ]
