FROM node:17.3.1-alpine3.15
LABEL maintainer="Daniel Rataj <daniel.rataj@centrum.cz>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

RUN apk add --no-cache docker-cli=20.10.16-r0 \
  jq=1.6-r1 \
  bash=5.1.16-r0 \
  && rm -rf /var/cache/apk/*

WORKDIR /app

# copy required app files
COPY image-metadata/ .
RUN npm install --quiet

# wait for container
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /opt/bin/
RUN chmod +x /opt/bin/wait-for-it.sh

# start worker
CMD ["/opt/bin/wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
