FROM node:14.11.0-alpine3.12
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@centrum.cz>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

# set a working directory
WORKDIR /app

# copy source code to WORKDIR
COPY monitor/ .

# install quasar globally
RUN yarn global add @quasar/cli@1.1.0

# install dependencies
RUN yarn install

COPY monitor/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

# expose port for Node server
EXPOSE 80
