FROM node:15.2.1-alpine3.12
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@centrum.cz>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

RUN apk add --no-cache openssl=1.1.1g-r0 \
    docker-cli=19.03.12-r0 \
    docker-compose=1.25.4-r2 && \
    rm -rf /var/cache/apk/*

WORKDIR /app

# copy required app files
COPY installer/ .
RUN npm install --quiet

VOLUME .:/output/

ENTRYPOINT [ "npm" ]
