FROM node:18.10.0-alpine3.15
LABEL maintainer="Daniel Rataj <info@whoopsmonitor.app>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

# set a working directory
WORKDIR /app

# copy source code to WORKDIR
COPY monitor/ .

# install quasar globally
RUN yarn global add @quasar/cli@1.3.2

# install dependencies
RUN yarn install && yarn cache clean

COPY monitor/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

# expose port for Node server
EXPOSE 80
