FROM node:18.10.0-alpine3.15
LABEL maintainer="Daniel Rataj <info@whoopsmonitor.app>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

RUN apk add --no-cache openssl=1.1.1q-r0 \
    docker-cli=20.10.16-r0 \
    bash=5.1.16-r0 \
  && rm -rf /var/cache/apk/*

WORKDIR /app

# copy required app files
COPY worker/ .
RUN npm install --quiet

# wait for container
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /opt/bin/
RUN chmod +x /opt/bin/wait-for-it.sh

# start worker
CMD ["/opt/bin/wait-for-it.sh", "whoopsmonitor-api:1337", "--", "npm", "start"]
