FROM node:14.11.0-alpine3.12
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@centrum.cz>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

RUN apk add --no-cache docker-cli=20.10.3-r0 jq=1.6-r1 \
  && rm -rf /var/cache/apk/*

WORKDIR /app

# copy required app files
COPY image-metadata/ .
RUN npm install --quiet

# start worker
CMD [ "npm", "start" ]
