FROM node:15.2.1-alpine3.12
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@centrum.cz>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

RUN apk add --no-cache openssl=1.1.1i-r0 \
    docker-cli=19.03.12-r0 \
    docker-compose=1.25.4-r3 && \
    curl=7.74.0-r0 && \
    rm -rf /var/cache/apk/*

WORKDIR /app

# copy required app files
COPY installer/ .
RUN npm install --quiet

VOLUME .:/output/

COPY installer/entrypoint.sh /opt/whoopsmonitor/entrypoint.sh
RUN chmod +x /opt/whoopsmonitor/entrypoint.sh

ENTRYPOINT ["/opt/whoopsmonitor/entrypoint.sh"]
