FROM node:15.14.0-alpine3.13
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@centrum.cz>"
LABEL org.opencontainers.image.source="https://github.com/whoopsmonitor/whoopsmonitor"

RUN apk add --no-cache openssl=1.1.1k-r0 \
  docker-cli=20.10.3-r1 \
  && rm -rf /var/cache/apk/*

WORKDIR /app

# copy required app files
COPY worker/ .
RUN npm install --quiet

# start worker
CMD [ "npm", "start" ]
